select * from PRISONER


show * from koko databases;

show tables;



SELECT DATABASE();
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema koko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koko` DEFAULT CHARACTER SET utf8 ;
USE `koko` ;

-- -----------------------------------------------------
-- Table `koko`.`PRISONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`PRISONER` (
  `PRISON_NUMBER` INT NOT NULL,
  ` NAME` VARCHAR(45) NULL,
  `AGE` INT NULL,
  `SEX` VARCHAR(45) NULL,
  `PRISON_AREA` VARCHAR(45) NULL,
  `ROOM_NUMBER` INT NULL,
  `CRIME_CLASSIFICATION` VARCHAR(45) NULL,
  `BEFORE` VARCHAR(45) NULL,
  `PHOTO` VARCHAR(45) NULL,
  PRIMARY KEY (`PRISON_NUMBER`))
ENGINE = InnoDB;

select * from PRISONER
insert into PRISONER(PRISON_NUMBER,NAME,AGE,SEX,PRISON_AREA,ROOM_NUMBER,CRIME_CLASSIFICATION,BEFORE,PHOTO) values('1','1','1','1','1','1','1','1','0');
-- -----------------------------------------------------
-- Table `koko`.`SPECIAL_MANAGEMENT_PERSONNEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`SPECIAL_MANAGEMENT_PERSONNEL` (
  `SPECIAL_ADMIN_NUMBER` INT NOT NULL,
  `REASON` VARCHAR(45) NOT NULL,
  `MANAGEMENT_GRADE` INT NOT NULL,
  `PRISONER_PRISON_NUMBER` INT NOT NULL,
  PRIMARY KEY (`SPECIAL_ADMIN_NUMBER`),
  INDEX `fk_SPECIAL_MANAGEMENT_PERSONNEL_PRISONER_idx` (`PRISONER_PRISON_NUMBER` ASC),
  CONSTRAINT `fk_SPECIAL_MANAGEMENT_PERSONNEL_PRISONER`
    FOREIGN KEY (`PRISONER_PRISON_NUMBER`)
    REFERENCES `koko`.`PRISONER` (`PRISON_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from SPECIAL_MANAGEMENT_PERSONNEL
insert into SPECIAL_MANAGEMENT_PERSONNEL(SPECIAL_ADMIN_NUMBER,REASON,MANAGEMENT_GRADE,PRISONER_PRISON_NUMBER) values('2','2','2','1');
-- -----------------------------------------------------
-- Table `koko`.`CCTV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`CCTV` (
  `CCTV_NO` VARCHAR(45) NOT NULL,
  `AREA` VARCHAR(45) NULL,
  `CCTV_NON` VARCHAR(45) NULL,
  `LOCATION` VARCHAR(45) NULL,
  `ACTIVE` BLOB NULL,
  `UNIQUE` VARCHAR(45) NULL,
  PRIMARY KEY (`CCTV_NO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`PRISON_OFFICER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`PRISON_OFFICER` (
  `PO_NO` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `AGE` VARCHAR(45) NULL,
  `GENDER` VARCHAR(45) NULL,
  `RANK` VARCHAR(45) NULL,
  `POSITION` VARCHAR(45) NULL,
  `DEPARTMENT` VARCHAR(45) NULL,
  `PRISON_OFFICERcol` VARCHAR(45) NULL,
  `PHOTO` BLOB NULL,
  `PRISONER_PRISON_NUMBER` INT NOT NULL,
  PRIMARY KEY (`PO_NO`),
  INDEX `fk_PRISON_OFFICER_PRISONER1_idx` (`PRISONER_PRISON_NUMBER` ASC),
  CONSTRAINT `fk_PRISON_OFFICER_PRISONER1`
    FOREIGN KEY (`PRISONER_PRISON_NUMBER`)
    REFERENCES `koko`.`PRISONER` (`PRISON_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`ANOMALY_DETECTION_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`ANOMALY_DETECTION_HISTORY` (
  `ABNORMAL_HISTORY_NUMBER` INT NOT NULL,
  `ALERT_DATE` DATE NULL,
  `ANOMALIES` VARCHAR(45) NULL,
  `ACTUAL_ANOMALIES` VARCHAR(45) NULL,
  `PRISON_NUMBER` INT NULL,
  `CCTV_CCTV_NO` VARCHAR(45) NOT NULL,
  `PRISON_OFFICER_PO_NO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ABNORMAL_HISTORY_NUMBER`, `CCTV_CCTV_NO`),
  INDEX `fk_ANOMALY_DETECTION_HISTORY_CCTV1_idx` (`CCTV_CCTV_NO` ASC),
  INDEX `fk_ANOMALY_DETECTION_HISTORY_PRISON_OFFICER1_idx` (`PRISON_OFFICER_PO_NO` ASC),
  CONSTRAINT `fk_ANOMALY_DETECTION_HISTORY_CCTV1`
    FOREIGN KEY (`CCTV_CCTV_NO`)
    REFERENCES `koko`.`CCTV` (`CCTV_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANOMALY_DETECTION_HISTORY_PRISON_OFFICER1`
    FOREIGN KEY (`PRISON_OFFICER_PO_NO`)
    REFERENCES `koko`.`PRISON_OFFICER` (`PO_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`PRISON_OFFICER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`PRISON_OFFICER` (
  `PO_NO` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `AGE` VARCHAR(45) NULL,
  `GENDER` VARCHAR(45) NULL,
  `RANK` VARCHAR(45) NULL,
  `POSITION` VARCHAR(45) NULL,
  `DEPARTMENT` VARCHAR(45) NULL,
  `PRISON_OFFICERcol` VARCHAR(45) NULL,
  `PHOTO` BLOB NULL,
  `PRISONER_PRISON_NUMBER` INT NOT NULL,
  PRIMARY KEY (`PO_NO`),
  INDEX `fk_PRISON_OFFICER_PRISONER1_idx` (`PRISONER_PRISON_NUMBER` ASC),
  CONSTRAINT `fk_PRISON_OFFICER_PRISONER1`
    FOREIGN KEY (`PRISONER_PRISON_NUMBER`)
    REFERENCES `koko`.`PRISONER` (`PRISON_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`PATROL_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`PATROL_HISTORY` (
  `PH_NO` VARCHAR(45) NOT NULL,
  `DATE` DATE NULL,
  `TIME` VARCHAR(45) NULL,
  `LOCATION` VARCHAR(45) NULL,
  `CONTENTS` VARCHAR(45) NULL,
  `PRISON_OFFICER_PO_NO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PH_NO`),
  INDEX `fk_PATROL_HISTORY_PRISON_OFFICER1_idx` (`PRISON_OFFICER_PO_NO` ASC),
  CONSTRAINT `fk_PATROL_HISTORY_PRISON_OFFICER1`
    FOREIGN KEY (`PRISON_OFFICER_PO_NO`)
    REFERENCES `koko`.`PRISON_OFFICER` (`PO_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`DRUG_MANAGEMENT_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`DRUG_MANAGEMENT_HISTORY` (
  `DM_NO` INT NOT NULL,
  `DRUG_TYPE` VARCHAR(45) NULL,
  `SPEC_DRUG` BLOB NULL,
  `DRUG_COUNT` VARCHAR(45) NULL,
  `PRISONER_PRISON_NUMBER` INT NOT NULL,
  PRIMARY KEY (`DM_NO`),
  INDEX `fk_DRUG_MANAGEMENT_HISTORY_PRISONER1_idx` (`PRISONER_PRISON_NUMBER` ASC),
  CONSTRAINT `fk_DRUG_MANAGEMENT_HISTORY_PRISONER1`
    FOREIGN KEY (`PRISONER_PRISON_NUMBER`)
    REFERENCES `koko`.`PRISONER` (`PRISON_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`SPEC_DRUG_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`SPEC_DRUG_HISTORY` (
  `TH_NO` VARCHAR(45) NOT NULL,
  `TAKING_DATE` DATE NULL,
  `DRUG_MANAGEMENT_HISTORY_DM_NO` INT NOT NULL,
  PRIMARY KEY (`TH_NO`),
  INDEX `fk_SPEC_DRUG_HISTORY_DRUG_MANAGEMENT_HISTORY1_idx` (`DRUG_MANAGEMENT_HISTORY_DM_NO` ASC),
  CONSTRAINT `fk_SPEC_DRUG_HISTORY_DRUG_MANAGEMENT_HISTORY1`
    FOREIGN KEY (`DRUG_MANAGEMENT_HISTORY_DM_NO`)
    REFERENCES `koko`.`DRUG_MANAGEMENT_HISTORY` (`DM_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koko`.`PRISONER_has_ANOMALY_DETECTION_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koko`.`PRISONER_has_ANOMALY_DETECTION_HISTORY` (
  `PRISONER_PRISON_NUMBER` INT NOT NULL,
  `ANOMALY_DETECTION_HISTORY_ABNORMAL_HISTORY_NUMBER` INT NOT NULL,
  PRIMARY KEY (`PRISONER_PRISON_NUMBER`, `ANOMALY_DETECTION_HISTORY_ABNORMAL_HISTORY_NUMBER`),
  INDEX `fk_PRISONER_has_ANOMALY_DETECTION_HISTORY_ANOMALY_DETECTION_idx` (`ANOMALY_DETECTION_HISTORY_ABNORMAL_HISTORY_NUMBER` ASC),
  INDEX `fk_PRISONER_has_ANOMALY_DETECTION_HISTORY_PRISONER1_idx` (`PRISONER_PRISON_NUMBER` ASC),
  CONSTRAINT `fk_PRISONER_has_ANOMALY_DETECTION_HISTORY_PRISONER1`
    FOREIGN KEY (`PRISONER_PRISON_NUMBER`)
    REFERENCES `koko`.`PRISONER` (`PRISON_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRISONER_has_ANOMALY_DETECTION_HISTORY_ANOMALY_DETECTION_H1`
    FOREIGN KEY (`ANOMALY_DETECTION_HISTORY_ABNORMAL_HISTORY_NUMBER`)
    REFERENCES `koko`.`ANOMALY_DETECTION_HISTORY` (`ABNORMAL_HISTORY_NUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
